version: '2'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU13-ubuntu
    container_name: docker-itshare-sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Qwerty123
      MSSQL_PID: Developer
    volumes:
      - sqldata:/var/opt/mssql
  redis:
    image: redis:5.0.4-alpine3.9
    container_name: docker-itshare-redis
    ports:
    - 6379:6379
volumes:
  sqldata:
